# Vista26: High-Precision Retail Product Detection & Classification

This repository contains a specialized computer vision pipeline designed for the Vista26 Retail Challenge. The project implements a "Spatial Ensemble" architecture that decouples the task of finding products (Agnostic Detection) from the task of identifying them (Classification).

## Model Architecture & Choice

To achieve 97% accuracy, we moved away from a single-model approach in favor of a specialized ensemble system that treats localization and categorization as distinct problems.

### 1. Agnostic Detectors (The "Where")
* **Models:** YOLOv11s and YOLO26s
* **Role:** These models were fine-tuned as binary detectors (Product vs. Background).
* **Selection Logic:** * **YOLO26s:** This model was chosen for its native end-to-end NMS-free inference. By eliminating the post-processing Non-Maximum Suppression bottleneck, it provides faster and more stable predictions. Furthermore, its Small-Target-Aware Labeling (STAL) mechanism specifically improves the detection of small, dense retail items like energy bars or spice packets.
    * **YOLOv11s:** Selected to complement YOLO26s by acting as a high-recall observer. While YOLO26s optimizes for speed and small targets, YOLOv11s provides robustness against varying lighting and partially obscured products.
* **Ensemble Mechanism:** We utilize a "Redundancy-First" detection ensemble. Predictions from both models are aggregated and then merged via Non-Maximum Suppression (NMS). This ensures that a product missed by one model is likely caught by the other, maximizing total object recall before the classification stage.



### 2. Labeling Classifiers (The "What")
* **Models:** YOLOv10s and YOLOv11s
* **Role:** These models identify the specific category (1–200) for the regions proposed by the detectors.
* **Selection Logic:**
    * **YOLOv10s:** Chosen for its superior efficiency in processing large volumes of proposed regions. It provides a highly accurate baseline for standard product forms.
    * **YOLOv11s:** Integrated to provide a secondary "expert" opinion. It excels at distinguishing between products with high visual similarity (e.g., different flavors of the same brand).
* **Ensemble Mechanism:** We implement "Maximum Confidence Voting." Rather than simple averaging, the system compares the confidence scores assigned by both classifiers to a specific bounding box. The label from the model with the higher statistical certainty is selected, which effectively resolves conflicts in ambiguous cases and reduces classification noise.

## Data Processing Pipeline

The initial data processing was designed to handle the complexity of the 200-class retail dataset:

* **JSON Normalization:** COCO-style instances.json and Categories.json were flattened into optimized Pandas DataFrames. This allowed for O(1) complexity lookups during the evaluation loop, significantly speeding up the validation process.
* **Agnostic Re-mapping:** To train the detectors, we re-mapped all 200 category IDs to a single class (0: product). By removing the need to differentiate between classes, the detectors could focus their entire parameter budget on "objectness" and spatial precision.
* **High-Resolution Tiling:** Retail environments suffer from severe scale variance. We processed images at resolutions up to 1024px, ensuring that the feature maps retained enough detail to localise items located on the back of shelves.

## Inference Logic: Spatial Gating

The final submission is generated using a Spatial Gating algorithm:

1. **Detection Ensemble:** Aggregated predictions from YOLO11s and YOLO26s are filtered to create a "Master List" of product locations.
2. **Dual-Classifier Matching:** Each Master Box is spatially matched against predictions from our two classifiers using an Intersection over Union (IoU) threshold of 0.15.
3. **Confidence Voting:** If both classifiers provide a label for a box, the script selects the label with the higher confidence score. If no match is found, the system defaults to a baseline class to maintain count integrity.

In [1]:
!pip install ultralytics --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 21.4 MB/s eta 0:00:00a 0:00:01

In [2]:
import json

# Replace with your specific file path
file_path = '/kaggle/input/vista26/Vistas Dataset Public/Vistas Dataset Public/Categories.json'

with open(file_path, 'r') as f:
    data = json.load(f)

# Now 'data' is a standard Python dictionary or list
#print(data)
import pandas as pd

# Assuming your data is stored in a variable called 'data'
df_cat = pd.DataFrame(data['categories'])
df_cat.rename(columns = {'id':'category_id'}, inplace = True)
# Display the first few rows in a clean table
df_cat.head(15)

   supercategory  category_id            name
0    puffed_food            1   1_puffed_food
1    puffed_food            2   2_puffed_food
2    puffed_food            3   3_puffed_food
3    puffed_food            4   4_puffed_food
4    puffed_food            5   5_puffed_food
5    puffed_food            6   6_puffed_food
6    puffed_food            7   7_puffed_food
7    puffed_food            8   8_puffed_food
8    puffed_food            9   9_puffed_food
9    puffed_food           10  10_puffed_food
10   puffed_food           11  11_puffed_food
11   puffed_food           12  12_puffed_food
12   dried_fruit           13  13_dried_fruit
13   dried_fruit           14  14_dried_fruit
14   dried_fruit           15  15_dried_fruit

In [3]:
import json
import pandas as pd

# Replace with your specific file path
file_path = '/kaggle/input/vista26/Vistas Dataset Public/Vistas Dataset Public/instances_test.json'

with open(file_path, 'r') as f:
    data = json.load(f)
print(data.keys())
test_images=data["images"]
test_annotations = data["annotations"]
df_test_image=pd.DataFrame(test_images)
df_test_image.rename(columns = {'id':'image_id'}, inplace = True)
print(df_test_image.head(15))
df_test_ann = pd.DataFrame(test_annotations)
print(df_test_ann.head(15))

dict_keys(['images', 'annotations'])
                     file_name  width  height  image_id   level
0    20180912-10-30-36-180.jpg   1774    1774     30075    hard
1    20180824-16-59-34-524.jpg   1844    1844      1912    easy
2   20181016-11-01-36-1817.jpg   1846    1846     11523  medium
3    20180910-15-58-47-974.jpg   1806    1806     10662  medium
4   20181017-14-51-04-2215.jpg   1836    1836     15314  medium
5   20181018-10-01-39-2303.jpg   1852    1852     11604  medium
6    20180827-09-07-51-102.jpg   1818    1818       746    easy
7     20181025-10-00-14-29.jpg   1824    1824       592    easy
8   20180904-09-31-53-2747.jpg   1852    1852      4380    easy
9   20180903-14-15-16-2613.jpg   1847    1847      8289    easy
10  20181012-14-47-39-1353.jpg   1835    1835     18474  medium
11  20181018-14-48-18-2904.jpg   1858    1858     17517  medium
12  20180828-15-08-23-1183.jpg   1848    1848      2215    easy
13  20180925-16-09-00-1643.jpg   1862    1862     24953    hard
14   20180912-16-32-03-353.jpg   1848    1848     20492    hard
         area                               bbox  category_id  id  image_id  \
0   149040.14  [896.74, 1032.48, 322.61, 461.98]          181   9         3
1   261450.66   [451.22, 785.58, 478.44, 546.47]            8  10         3
2    93244.76    [793.51, 732.3, 279.87, 333.18]           45  11         3
3   415934.14   [566.95, 288.82, 656.82, 633.25]            8  12         4
4   217678.17    [887.5, 713.08, 455.69, 477.69]          181  13         4
5   115406.97   [593.66, 882.79, 322.13, 358.27]           45  14         4
6   103733.48  [1153.52, 823.96, 308.59, 336.15]           45  15         5
7   336601.69    [587.03, 410.67, 590.74, 569.8]            8  16         5
8   190610.35   [536.54, 855.32, 477.93, 398.82]          181  17         5
9    40634.78  [1059.06, 835.11, 107.65, 377.46]          130  18         6
10  137357.16   [633.38, 727.41, 356.55, 385.24]           39  19         6
11   81350.24   [491.8, 1139.02, 389.83, 208.68]          127  20         6
12  204647.88    [547.56, 655.9, 450.65, 454.11]           39  21         7
13   38377.94  [1317.48, 704.31, 103.73, 369.97]          130  22         7
14  120238.93   [411.56, 995.91, 390.72, 307.74]          127  23         7

    iscrowd segmentation            point_xy
0         0         [[]]  [1058.05, 1263.47]
1         0         [[]]   [690.44, 1058.82]
2         0         [[]]    [933.44, 898.89]
3         0         [[]]    [895.36, 605.44]
4         0         [[]]   [1115.35, 951.93]
5         0         [[]]   [754.72, 1061.92]
6         0         [[]]   [1307.82, 992.04]
7         0         [[]]     [882.4, 695.57]
8         0         [[]]    [775.5, 1054.73]
9         0         [[]]  [1112.88, 1023.84]
10        0         [[]]    [811.65, 920.03]
11        0         [[]]   [686.72, 1243.36]
12        0         [[]]    [772.88, 882.95]
13        0         [[]]   [1369.35, 889.29]
14        0         [[]]   [606.92, 1149.78]

In [4]:
merged_test_df = pd.merge(df_test_image, df_test_ann, on = 'image_id')
merged_test_df.head(15)

,file_name,width,height,image_id,level,area,bbox,category_id,id,iscrowd,segmentation,point_xy
0,20180912-10-30-36-180.jpg,1774,1774,30075,hard,208726.41,"[778.15, 241.58, 372.26, 560.69]",173,365188,0,[[]],"[964.28, 521.93]"
1,20180912-10-30-36-180.jpg,1774,1774,30075,hard,109014.85,"[1404.99, 141.78, 196.97, 553.47]",173,365189,0,[[]],"[1503.47, 418.51]"
2,20180912-10-30-36-180.jpg,1774,1774,30075,hard,376430.89,"[1109.54, 531.78, 610.59, 616.5]",8,365190,0,[[]],"[1414.84, 840.03]"
3,20180912-10-30-36-180.jpg,1774,1774,30075,hard,214999.56,"[1103.63, 317.08, 399.84, 537.71]",78,365191,0,[[]],"[1303.55, 585.93]"
4,20180912-10-30-36-180.jpg,1774,1774,30075,hard,56822.83,"[1155.55, 125.18, 150.26, 378.17]",129,365192,0,[[]],"[1230.68, 314.26]"
5,20180912-10-30-36-180.jpg,1774,1774,30075,hard,44293.17,"[1057.63, 201.16, 118.18, 374.8]",129,365193,0,[[]],"[1116.72, 388.56]"
6,20180912-10-30-36-180.jpg,1774,1774,30075,hard,212926.22,"[731.79, 321.02, 391.68, 543.62]",73,365194,0,[[]],"[927.63, 592.83]"
7,20180912-10-30-36-180.jpg,1774,1774,30075,hard,130057.72,"[627.12, 280.5, 219.48, 592.58]",78,365195,0,[[]],"[736.86, 576.79]"
8,20180912-10-30-36-180.jpg,1774,1774,30075,hard,302356.25,"[255.7, 309.21, 459.21, 658.43]",28,365196,0,[[]],"[485.3, 638.42]"
9,20180912-10-30-36-180.jpg,1774,1774,30075,hard,107585.18,"[1065.22, 878.15, 301.0, 357.43]",152,365197,0,[[]],"[1215.72, 1056.87]"
10,20180912-10-30-36-180.jpg,1774,1774,30075,hard,224967.94,"[685.26, 604.65, 485.6, 463.28]",78,365198,0,[[]],"[928.06, 836.29]"
11,20180912-10-30-36-180.jpg,1774,1774,30075,hard,320581.66,"[694.56, 759.08, 455.83, 703.29]",28,365199,0,[[]],"[922.47, 1110.72]"
12,20180912-10-30-36-180.jpg,1774,1774,30075,hard,31446.90,"[216.57, 734.36, 209.14, 150.36]",189,365200,0,[[]],"[321.14, 809.54]"
13,20180912-10-30-36-180.jpg,1774,1774,30075,hard,98240.29,"[183.77, 860.12, 277.49, 354.04]",152,365201,0,[[]],"[322.51, 1037.14]"
14,20180912-10-30-36-180.jpg,1774,1774,30075,hard,354404.53,"[282.18, 887.46, 548.14, 646.56]",11,365202,0,[[]],"[556.25, 1210.74]"

In [5]:
merged_test_cat_df = pd.merge(merged_test_df, df_cat, on = 'category_id')
merged_test_cat_df.head(15)

,file_name,width,height,image_id,level,area,bbox,category_id,id,iscrowd,segmentation,point_xy,supercategory,name
0,20180912-10-30-36-180.jpg,1774,1774,30075,hard,208726.41,"[778.15, 241.58, 372.26, 560.69]",173,365188,0,[[]],"[964.28, 521.93]",personal_hygiene,173_personal_hygiene
1,20180912-10-30-36-180.jpg,1774,1774,30075,hard,109014.85,"[1404.99, 141.78, 196.97, 553.47]",173,365189,0,[[]],"[1503.47, 418.51]",personal_hygiene,173_personal_hygiene
2,20180912-10-30-36-180.jpg,1774,1774,30075,hard,376430.89,"[1109.54, 531.78, 610.59, 616.5]",8,365190,0,[[]],"[1414.84, 840.03]",puffed_food,8_puffed_food
3,20180912-10-30-36-180.jpg,1774,1774,30075,hard,214999.56,"[1103.63, 317.08, 399.84, 537.71]",78,365191,0,[[]],"[1303.55, 585.93]",drink,78_drink
4,20180912-10-30-36-180.jpg,1774,1774,30075,hard,56822.83,"[1155.55, 125.18, 150.26, 378.17]",129,365192,0,[[]],"[1230.68, 314.26]",chocolate,129_chocolate
5,20180912-10-30-36-180.jpg,1774,1774,30075,hard,44293.17,"[1057.63, 201.16, 118.18, 374.8]",129,365193,0,[[]],"[1116.72, 388.56]",chocolate,129_chocolate
6,20180912-10-30-36-180.jpg,1774,1774,30075,hard,212926.22,"[731.79, 321.02, 391.68, 543.62]",73,365194,0,[[]],"[927.63, 592.83]",drink,73_drink
7,20180912-10-30-36-180.jpg,1774,1774,30075,hard,130057.72,"[627.12, 280.5, 219.48, 592.58]",78,365195,0,[[]],"[736.86, 576.79]",drink,78_drink
8,20180912-10-30-36-180.jpg,1774,1774,30075,hard,302356.25,"[255.7, 309.21, 459.21, 658.43]",28,365196,0,[[]],"[485.3, 638.42]",dried_food,28_dried_food
9,20180912-10-30-36-180.jpg,1774,1774,30075,hard,107585.18,"[1065.22, 878.15, 301.0, 357.43]",152,365197,0,[[]],"[1215.72, 1056.87]",seasoner,152_seasoner
10,20180912-10-30-36-180.jpg,1774,1774,30075,hard,224967.94,"[685.26, 604.65, 485.6, 463.28]",78,365198,0,[[]],"[928.06, 836.29]",drink,78_drink
11,20180912-10-30-36-180.jpg,1774,1774,30075,hard,320581.66,"[694.56, 759.08, 455.83, 703.29]",28,365199,0,[[]],"[922.47, 1110.72]",dried_food,28_dried_food
12,20180912-10-30-36-180.jpg,1774,1774,30075,hard,31446.90,"[216.57, 734.36, 209.14, 150.36]",189,365200,0,[[]],"[321.14, 809.54]",tissue,189_tissue
13,20180912-10-30-36-180.jpg,1774,1774,30075,hard,98240.29,"[183.77, 860.12, 277.49, 354.04]",152,365201,0,[[]],"[322.51, 1037.14]",seasoner,152_seasoner
14,20180912-10-30-36-180.jpg,1774,1774,30075,hard,354404.53,"[282.18, 887.46, 548.14, 646.56]",11,365202,0,[[]],"[556.25, 1210.74]",puffed_food,11_puffed_food

In [6]:
# Run this once to fix the range
merged_test_cat_df['category_id'] = merged_test_cat_df['category_id'] - 1

# Verify the fix
print(f"New Min label: {merged_test_cat_df['category_id'].min()}") # Should be 0
print(f"New Max label: {merged_test_cat_df['category_id'].max()}") # Should be 199

New Min label: 0
New Max label: 199

In [7]:
import os
import pandas as pd
from PIL import Image
from tqdm import tqdm

# 1. Define paths
image_dir = '/kaggle/input/vista26/Vistas Dataset Public/Vistas Dataset Public/test'
output_labels_dir = '/kaggle/working/dataset/train/labels' # Where .txt files will go
os.makedirs(output_labels_dir, exist_ok=True)

def convert_to_yolo(df, img_folder, out_folder):
    # Group by file_name so we create one .txt per image
    grouped = df.groupby('file_name')
    
    for file_name, group in tqdm(grouped, desc="Converting to YOLO format"):
        # We need the image dimensions for normalization
        img_path = os.path.join(img_folder, file_name)
        if not os.path.exists(img_path):
            continue
            
        with Image.open(img_path) as img:
            img_w, img_h = img.size
            
        # Create the .txt filename (e.g., image1.jpg -> image1.txt)
        txt_name = os.path.splitext(file_name)[0] + ".txt"
        txt_path = os.path.join(out_folder, txt_name)
        
        with open(txt_path, 'w') as f:
            for _, row in group.iterrows():
                # Extract COCO: [x_min, y_min, width, height]
                x_min, y_min, w, h = row['bbox']
                class_id = int(row['category_id']) # Should be 0-199
                
                # 2. Convert to YOLO format (x_center, y_center, width, height)
                x_center = x_min + (w / 2)
                y_center = y_min + (h / 2)
                
                # 3. Normalize (divide by image dimensions)
                x_norm = x_center / img_w
                y_norm = y_center / img_h
                w_norm = w / img_w
                h_norm = h / img_h
                
                # 4. Write to file (class_id x y w h)
                # We use 6 decimal places for precision
                f.write(f"{class_id} {x_norm:.6f} {y_norm:.6f} {w_norm:.6f} {h_norm:.6f}\n")

# Run the conversion
convert_to_yolo(merged_test_cat_df, image_dir, output_labels_dir)

Converting to YOLO format: 100%|██████████| 18000/18000 [02:59<00:00, 100.23it/s]

In [8]:
# Create a dictionary mapping category_id to name
# We sort by category_id to ensure the indices match YOLO's expectations
class_mapping = merged_test_cat_df[['category_id', 'name']].drop_duplicates()
class_mapping = class_mapping.sort_values('category_id')

# Convert to a dictionary: {0: 'puffed_food', 1: 'juice', ...}
names_dict = dict(zip(class_mapping['category_id'], class_mapping['name']))

In [9]:
import os

# Define the root for your YOLO dataset
base_dir = '/kaggle/working/dataset/train'
images_dest = os.path.join(base_dir, 'images')
labels_dest = os.path.join(base_dir, 'labels')

# Create the folders
os.makedirs(images_dest, exist_ok=True)
os.makedirs(labels_dest, exist_ok=True)

In [10]:
import subprocess
from tqdm import tqdm

# Source path where the actual images live
images_src = '/kaggle/input/vista26/Vistas Dataset Public/Vistas Dataset Public/test'

# 1. Symlink Images
print("Creating image symlinks...")
# We use a shell command for speed; it links all files from src to dest
subprocess.run(f"ln -s '{images_src}'/* '{images_dest}'/", shell=True)

Creating image symlinks...

CompletedProcess(args="ln -s '/kaggle/input/vista26/Vistas Dataset Public/Vistas Dataset Public/test'/* '/kaggle/working/dataset/train/images'/", returncode=0)

In [ ]:


# 2. Link/Move Labels
# Assuming your labels were generated in '/kaggle/working/labels'
labels_src = '/kaggle/input/vista26-labels'

print("Linking labels...")
# If labels are already in working, we can just move or link them
subprocess.run(f"ln -s '{labels_src}'/* '{labels_dest}'/", shell=True)

# Verification
img_count = len(os.listdir(images_dest))
lbl_count = len(os.listdir(labels_dest))
print(f"Done! Linked {img_count} images and {lbl_count} labels.")

In [11]:
# Verification
img_count = len(os.listdir(images_dest))
lbl_count = len(os.listdir(labels_dest))
print(f"Done! Linked {img_count} images and {lbl_count} labels.")

Done! Linked 18000 images and 18000 labels.

In [12]:
import os
import random

image_files = [os.path.join('/kaggle/working/dataset/train/images', f) for f in os.listdir('/kaggle/working/dataset/train/images')]
random.shuffle(image_files)

# Split 80% for "fake" training, 20% for "real" validation
split = int(0.8 * len(image_files))
train_list = image_files[:]
val_list = image_files[split:]

with open('/kaggle/working/dataset/train_images.txt', 'w') as f:
    for path in train_list: f.write(path + '\n')

with open('/kaggle/working/dataset/val_images.txt', 'w') as f:
    for path in val_list: f.write(path + '\n')

In [13]:
import yaml

data_config = {
    # Paths to your data (Update these to your actual training/val paths)
    'path': '/',          # Base path
    'train': '/kaggle/working/dataset/train_images.txt',            # Train images (relative to path)
    'val': '/kaggle/working/dataset/val_images.txt',               # Val images (relative to path)
    
    # Number of classes
    'nc': 200,
    
    # Class names dictionary
    'names': names_dict
}

# Save to data.yaml
with open('/kaggle/working/data.yaml', 'w') as f:
    yaml.dump(data_config, f, default_flow_style=False, sort_keys=False)

print("data.yaml has been created successfully!")

data.yaml has been created successfully!

In [14]:
from ultralytics import YOLO

# Load the base YOLO26 model
model = YOLO('yolo26s.pt') 

# Fine-tune for Agnostic Detection
model.train(
    data='/kaggle/working/data.yaml',
    epochs=10,          # 25-50 is usually enough for agnostic specialization
    imgsz=640,         # High res for tiny product labels
    batch=-1,           # Auto-batch (finds the max your GPU can handle)
    augment=True,       # Crucial: enables mosaic and scale augmentations
    box=7.5,            # Increase box loss gain to prioritize coordinate precision
    cls=0.5,            # Lower class loss (since there's only 1 class)
    overlap_mask=True   # Helps the model distinguish between overlapping boxes
)

Creating new Ultralytics Settings v0.0.6 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26s.pt to 'yolo26s.pt': 100% ━━━━━━━━━━━━ 19.5MB 157.9MB/s 0.1s0.1s<0.1s
Ultralytics 8.4.9 🚀 Python-3.12.12 torch-2.8.0+cu126 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=True, auto_augment=randaugment, batch=-1, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/working/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=10, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo26s.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=train, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/runs/detect/train, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 16.5MB/s 0.0s
Overriding model.yaml nc=80 with nc=200

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  3                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  4                  -1  1    103360  ultralytics.nn.modules.block.C3k2            [128, 256, 1, False, 0.25]
  5                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  6                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5, 3, True]
 10                  -1  1    990976  ultralytics.nn.modules.block.C2PSA           [512, 512, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    477184  ultralytics.nn.modules.block.C3k2            [768, 256, 1, True]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    136192  ultralytics.nn.modules.block.C3k2            [512, 128, 1, True]
 17                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 20                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1843712  ultralytics.nn.modules.block.C3k2            [768, 512, 1, True, 0.5, True]
 23        [16, 19, 22]  1   1086664  ultralytics.nn.modules.head.Detect           [200, 1, True, [128, 256, 512]]
YOLO26s summary: 260 layers, 10,102,664 parameters, 10,102,664 gradients, 23.4 GFLOPs

Transferred 696/708 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n.pt to 'yolo26n.pt': 100% ━━━━━━━━━━━━ 5.3MB 68.3MB/s 0.1s
AMP: checks passed ✅
train: Fast image access ✅ (ping: 1.4±1.8 ms, read: 274.5±125.3 MB/s, size: 253.0 KB)
train: Scanning /kaggle/working/dataset/train/labels... 18000 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 18000/18000 1.3Kit/s 13.8s0.1ss
train: New cache created: /kaggle/working/dataset/train/labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
AutoBatch: Computing optimal batch size for imgsz=640 at 60.0% CUDA memory utilization.
AutoBatch: CUDA:0 (Tesla T4) 14.56G total, 0.14G reserved, 0.12G allocated, 14.31G free
      Params      GFLOPs  GPU_mem (GB)  forward (ms) backward (ms)                   input                  output
    10102664       23.35         0.990         68.91           nan        (1, 3, 640, 640)                    list
    10102664       46.71         2.078          46.9           nan        (2, 3, 640, 640)                    list
    10102664       93.42         3.513         42.57           nan        (4, 3, 640, 640)                    list
    10102664       186.8         6.589         73.77           nan        (8, 3, 640, 640)                    list
    10102664       373.7        12.281         139.8           nan       (16, 3, 640, 640)                    list
AutoBatch: Using batch-size 11 for CUDA:0 8.91G/14.56G (61%) ✅
train: Fast image access ✅ (ping: 1.2±0.9 ms, read: 217.7±94.1 MB/s, size: 236.1 KB)
train: Scanning /kaggle/working/dataset/train/labels.cache... 18000 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 18000/18000 5.4Git/s 0.0s
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 257.7±109.4 MB/s, size: 190.5 KB)
val: Scanning /kaggle/working/dataset/train/labels... 3600 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 3600/3600 1.1Kit/s 3.4s0.0ss
val: New cache created: /kaggle/working/dataset/train/labels.cache
Plotting labels to /kaggle/working/runs/detect/train/labels.jpg...
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=4.9e-05, momentum=0.9) with parameter groups 114 weight(decay=0.0), 126 weight(decay=0.000515625), 126 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to /kaggle/working/runs/detect/train
Starting training for 10 epochs...
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/10      3.93G     0.6502      5.287   0.006455         44        640: 100% ━━━━━━━━━━━━ 1637/1637 3.3it/s 8:20<0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 164/164 3.2it/s 51.6s0.3ss
                   all       3600      43873      0.146     0.0876     0.0614      0.054

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/10      5.06G     0.5945      2.963    0.00582         35        640: 100% ━━━━━━━━━━━━ 1637/1637 3.5it/s 7:43<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 164/164 3.6it/s 45.4s0.3ss
                   all       3600      43873      0.512      0.506      0.534      0.464

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/10      5.06G     0.5819      1.533   0.005627         49        640: 100% ━━━━━━━━━━━━ 1637/1637 3.6it/s 7:39<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 164/164 3.6it/s 45.8s0.3ss
                   all       3600      43873      0.754      0.739       0.81      0.702

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/10      5.06G      0.571     0.9889    0.00551         48        640: 100% ━━━━━━━━━━━━ 1637/1637 3.6it/s 7:36<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 164/164 3.6it/s 45.5s0.3ss
                   all       3600      43873      0.845      0.831      0.903      0.786

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/10      5.06G     0.5619     0.7624   0.005401         64        640: 100% ━━━━━━━━━━━━ 1637/1637 3.6it/s 7:35<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 164/164 3.6it/s 45.5s0.3ss
                   all       3600      43873      0.878      0.869      0.933      0.813

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/10      5.08G     0.5552     0.6425   0.005332         35        640: 100% ━━━━━━━━━━━━ 1637/1637 3.6it/s 7:35<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 164/164 3.6it/s 45.2s0.3ss
                   all       3600      43873      0.901      0.891      0.949      0.828

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/10      5.08G     0.5513     0.5794   0.005283         51        640: 100% ━━━━━━━━━━━━ 1637/1637 3.6it/s 7:35<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 164/164 3.6it/s 45.6s0.3ss
                   all       3600      43873      0.908      0.896      0.952       0.83

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/10       5.1G     0.5467     0.5378    0.00525         47        640: 100% ━━━━━━━━━━━━ 1637/1637 3.6it/s 7:34<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 164/164 3.6it/s 45.4s0.3ss
                   all       3600      43873      0.915      0.908      0.959      0.838

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/10       5.1G     0.5453     0.5131   0.005205         41        640: 100% ━━━━━━━━━━━━ 1637/1637 3.6it/s 7:34<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 164/164 3.6it/s 45.2s0.3ss
                   all       3600      43873      0.922      0.911      0.961      0.841

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/10      5.15G     0.5423     0.4975    0.00522         56        640: 100% ━━━━━━━━━━━━ 1637/1637 3.6it/s 7:34<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 164/164 3.6it/s 45.8s0.3ss
                   all       3600      43873      0.924      0.912      0.963      0.842

10 epochs completed in 1.413 hours.
Optimizer stripped from /kaggle/working/runs/detect/train/weights/last.pt, 20.6MB
Optimizer stripped from /kaggle/working/runs/detect/train/weights/best.pt, 20.6MB

Validating /kaggle/working/runs/detect/train/weights/best.pt...
Ultralytics 8.4.9 🚀 Python-3.12.12 torch-2.8.0+cu126 CUDA:0 (Tesla T4, 14913MiB)
YOLO26s summary (fused): 122 layers, 9,542,580 parameters, 0 gradients, 21.0 GFLOPs
WARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 1% ──────────── 1/164 1.3it/s 0.2s<2:05WARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 1% ──────────── 2/164 2.0it/s 0.5s<1:22WARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 2% ──────────── 3/164 1.6it/s 1.9s<1:41WARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 2% ──────────── 4/164 2.2it/s 2.2s<1:13WARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 3% ──────────── 5/164 2.0it/s 2.8s<1:20WARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 4% ──────────── 6/164 3.0it/s 3.0s<52.2sWARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 4% ╸─────────── 7/164 3.5it/s 3.2s<44.8sWARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 8/164 3.9it/s 3.4s<39.7sWARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 9/164 4.2it/s 3.6s<36.6sWARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 6% ╸─────────── 10/164 4.6it/s 3.8s<33.7sWARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 7% ╸─────────── 11/164 4.6it/s 4.0s<33.1sWARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 7% ╸─────────── 12/164 4.7it/s 4.2s<32.5sWARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 8% ╸─────────── 13/164 4.7it/s 4.4s<32.3sWARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 9% ━─────────── 14/164 4.7it/s 4.7s<32.0sWARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 9% ━─────────── 15/164 4.6it/s 4.9s<32.1sWARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 16/164 4.7it/s 5.1s<31.8sWARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 17/164 4.6it/s 5.3s<31.8sWARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 11% ━─────────── 18/164 4.7it/s 5.5s<31.3sWARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 12% ━─────────── 19/164 4.7it/s 5.7s<30.9sWARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 12% ━─────────── 20/164 4.9it/s 5.9s<29.5sWARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 13% ━╸────────── 21/164 5.0it/s 6.1s<28.4sWARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 13% ━╸────────── 22/164 5.1it/s 6.3s<27.8sWARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 23/164 5.0it/s 6.5s<28.0sWARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 15% ━╸────────── 24/164 4.9it/s 6.7s<28.4sWARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 15% ━╸────────── 25/164 4.8it/s 6.9s<28.7sWARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 16% ━╸────────── 26/164 4.6it/s 7.2s<30.0sWARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 16% ━╸────────── 27/164 4.6it/s 7.4s<30.0sWARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 17% ━━────────── 28/164 4.6it/s 7.6s<29.6sWARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 18% ━━────────── 29/164 4.6it/s 7.8s<29.1sWARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 18% ━━────────── 30/164 4.7it/s 8.0s<28.7sWARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 31/164 4.7it/s 8.2s<28.3sWARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 20% ━━────────── 32/164 4.6it/s 8.5s<28.7sWARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.

ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123,
       124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185,
       186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x7ba2999fe840>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1, ...,     0.63455,     0.63455,           0],
       [          1,           1,           1, ...,     0.56306,     0.56306,           0],
       [          1,           1,           1, ...,     0.83824,     0.83824,           0],
       ...,
       [          1,           1,           1, ...,   0.0044828,   0.0022414,           0],
       [          1,           1,           1, ...,    0.072751,    0.072751,           0],
       [          1,           1,           1, ...,    0.032954,    0.016477,           0]]), 'Recall', 'Precision'], [array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,

In [ ]:
!pip install ultralytics --quiet
from ultralytics import YOLO

# Load a pretrained model
model = YOLO('yolo11s.pt') # 'n' for nano (fastest) or 's' for small

# Train
model.train(
    data='/kaggle/working/data.yaml',
    epochs=5,
    imgsz=512,
    batch=32,
    device=0 # Uses GPU
)

In [15]:
from ultralytics import YOLO

# 1. Load the "best" or "last" weights
model = YOLO('/kaggle/input/yolo-finetuned/pytorch/default/6/best_11s_extra.pt')

# 2. Start a NEW training run using those weights as a starting point
model.train(
    data='/kaggle/working/data.yaml',
    epochs=20,        # New target number of epochs
    imgsz=512,
    batch=32,
    device=0
)

Creating new Ultralytics Settings v0.0.6 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
Ultralytics 8.4.9 🚀 Python-3.12.12 torch-2.8.0+cu126 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/working/data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=20, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=512, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=/kaggle/input/yolo-finetuned/pytorch/default/6/best_11s_extra.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=train, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/runs/detect/train, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 28.5MB/s 0.0s

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  3                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  4                  -1  1    103360  ultralytics.nn.modules.block.C3k2            [128, 256, 1, False, 0.25]
  5                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  6                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1    990976  ultralytics.nn.modules.block.C2PSA           [512, 512, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    443776  ultralytics.nn.modules.block.C3k2            [768, 256, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    127680  ultralytics.nn.modules.block.C3k2            [512, 128, 1, False]
 17                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1    345472  ultralytics.nn.modules.block.C3k2            [384, 256, 1, False]
 20                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1511424  ultralytics.nn.modules.block.C3k2            [768, 512, 1, True]
 23        [16, 19, 22]  1    896808  ultralytics.nn.modules.head.Detect           [200, 16, None, [128, 256, 512]]
YOLO11s summary: 182 layers, 9,505,192 parameters, 9,505,176 gradients, 22.0 GFLOPs

Transferred 499/499 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n.pt to 'yolo26n.pt': 100% ━━━━━━━━━━━━ 5.3MB 89.6MB/s 0.1s
AMP: checks passed ✅
train: Fast image access ✅ (ping: 5.4±6.2 ms, read: 214.1±131.5 MB/s, size: 227.9 KB)
train: Scanning /kaggle/working/dataset/train/labels... 14400 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 14400/14400 971.2it/s 14.8s.1ss
train: New cache created: /kaggle/working/dataset/train/labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.5±0.0 ms, read: 389.7±56.9 MB/s, size: 278.0 KB)
val: Scanning /kaggle/working/dataset/train/labels... 3600 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 3600/3600 817.3it/s 4.4s.0s
val: New cache created: /kaggle/working/dataset/train/labels.cache
Plotting labels to /kaggle/working/runs/detect/train/labels.jpg...
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=4.9e-05, momentum=0.9) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.0005), 87 bias(decay=0.0)
Image sizes 512 train, 512 val
Using 4 dataloader workers
Logging results to /kaggle/working/runs/detect/train
Starting training for 20 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/20      5.87G     0.6419     0.5827      0.964        524        512: 100% ━━━━━━━━━━━━ 450/450 2.3it/s 3:13<0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.6it/s 35.9s0.5ss
                   all       3600      43787      0.976      0.975      0.991      0.857

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/20      5.86G     0.6415     0.5671     0.9635        614        512: 100% ━━━━━━━━━━━━ 450/450 2.4it/s 3:08<0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.9it/s 30.0s0.5ss
                   all       3600      43787      0.967      0.971       0.99      0.852

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/20      5.95G     0.6378     0.5469     0.9608        582        512: 100% ━━━━━━━━━━━━ 450/450 2.4it/s 3:04<0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.9it/s 29.5s0.5ss
                   all       3600      43787      0.976      0.975      0.992      0.859

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/20      5.92G     0.6324     0.5235     0.9601        568        512: 100% ━━━━━━━━━━━━ 450/450 2.4it/s 3:04<0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.9it/s 29.8s0.5ss
                   all       3600      43787      0.967       0.97      0.991      0.855

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/20      5.93G     0.6252     0.5033     0.9576        624        512: 100% ━━━━━━━━━━━━ 450/450 2.4it/s 3:05<0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.9it/s 29.9s0.5ss
                   all       3600      43787      0.974      0.978      0.992       0.86

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/20       5.9G     0.6222     0.4835     0.9565        682        512: 100% ━━━━━━━━━━━━ 450/450 2.4it/s 3:04<0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.9it/s 29.9s0.5ss
                   all       3600      43787      0.975      0.976      0.991      0.863

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/20      5.95G     0.6186     0.4729     0.9559        647        512: 100% ━━━━━━━━━━━━ 450/450 2.4it/s 3:05<0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.9it/s 29.7s0.5ss
                   all       3600      43787       0.99      0.987      0.994       0.87

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/20       5.9G     0.6132     0.4565      0.954        577        512: 100% ━━━━━━━━━━━━ 450/450 2.4it/s 3:05<0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.9it/s 29.5s0.5ss
                   all       3600      43787      0.987      0.986      0.994      0.866

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/20      5.96G     0.6098     0.4515     0.9524        576        512: 100% ━━━━━━━━━━━━ 450/450 2.4it/s 3:05<0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.9it/s 29.6s0.5ss
                   all       3600      43787      0.989      0.988      0.994       0.87

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/20       5.9G     0.6044      0.438     0.9515        605        512: 100% ━━━━━━━━━━━━ 450/450 2.4it/s 3:05<0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.9it/s 29.7s0.5ss
                   all       3600      43787      0.991      0.989      0.994      0.871
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/20      5.76G     0.5265     0.3124     0.9196        409        512: 100% ━━━━━━━━━━━━ 450/450 2.5it/s 3:02<0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.9it/s 29.5s0.5ss
                   all       3600      43787      0.988      0.989      0.994      0.873

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/20      5.75G     0.5231     0.3021     0.9184        367        512: 100% ━━━━━━━━━━━━ 450/450 2.5it/s 2:60<0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.9it/s 29.6s0.5ss
                   all       3600      43787      0.989      0.989      0.994      0.874

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/20      5.75G     0.5188     0.2943     0.9163        404        512: 100% ━━━━━━━━━━━━ 450/450 2.5it/s 2:60<0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.9it/s 29.8s0.5ss
                   all       3600      43787       0.99      0.991      0.994      0.875

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/20      5.75G     0.5156     0.2891     0.9149        387        512: 100% ━━━━━━━━━━━━ 450/450 2.5it/s 2:59<0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.9it/s 29.8s0.5ss
                   all       3600      43787      0.991      0.991      0.994      0.876

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/20      5.75G     0.5123     0.2842     0.9126        388        512: 100% ━━━━━━━━━━━━ 450/450 2.5it/s 2:59<0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.9it/s 29.7s0.5ss
                   all       3600      43787       0.99       0.99      0.994      0.876

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/20      5.76G     0.5104     0.2803     0.9122        406        512: 100% ━━━━━━━━━━━━ 450/450 2.5it/s 2:60<0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.9it/s 30.0s0.5ss
                   all       3600      43787      0.991      0.992      0.994      0.879

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/20      5.75G     0.5082     0.2794     0.9106        404        512: 100% ━━━━━━━━━━━━ 450/450 2.5it/s 2:60<0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.9it/s 29.3s0.5ss
                   all       3600      43787      0.992      0.992      0.994      0.878

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/20      5.75G     0.5068     0.2739     0.9095        390        512: 100% ━━━━━━━━━━━━ 450/450 2.5it/s 2:59<0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.9it/s 29.6s0.5ss
                   all       3600      43787      0.993      0.992      0.994      0.879

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/20      5.74G     0.5047     0.2733     0.9097        333        512: 100% ━━━━━━━━━━━━ 450/450 2.5it/s 2:59<0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.9it/s 29.6s0.5ss
                   all       3600      43787      0.993      0.992      0.994       0.88

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/20      5.75G      0.503     0.2702     0.9078        366        512: 100% ━━━━━━━━━━━━ 450/450 2.5it/s 2:60<0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.9it/s 29.4s0.5ss
                   all       3600      43787      0.993      0.993      0.995       0.88

20 epochs completed in 1.193 hours.
Optimizer stripped from /kaggle/working/runs/detect/train/weights/last.pt, 19.3MB
Optimizer stripped from /kaggle/working/runs/detect/train/weights/best.pt, 19.3MB

Validating /kaggle/working/runs/detect/train/weights/best.pt...
Ultralytics 8.4.9 🚀 Python-3.12.12 torch-2.8.0+cu126 CUDA:0 (Tesla T4, 14913MiB)
YOLO11s summary (fused): 101 layers, 9,490,200 parameters, 0 gradients, 21.7 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.8it/s 31.8s0.5ss
                   all       3600      43787      0.993      0.993      0.995       0.88
         1_puffed_food         66        136          1      0.997      0.995      0.938
         2_puffed_food        118        241      0.994          1      0.995      0.896
         3_puffed_food         75        138      0.993          1      0.995       0.94
         4_puffed_food        157        327      0.982          1      0.995       0.94
         5_puffed_food        108        205      0.968      0.995      0.994      0.932
         6_puffed_food         88        163      0.992      0.994      0.995       0.93
         7_puffed_food        135        272      0.994          1      0.995       0.94
         8_puffed_food        159        318          1      0.997      0.995      0.939
         9_puffed_food        103        210      0.995      0.998      0.995      0.901
        10_puffed_food        130        259      0.999          1      0.995      0.941
        11_puffed_food        161        313      0.996          1      0.995      0.917
        12_puffed_food        110        204      0.994          1      0.995      0.936
        13_dried_fruit        118        223      0.992      0.996      0.995      0.933
        14_dried_fruit        103        202      0.993          1      0.995      0.926
        15_dried_fruit        116        229          1      0.971      0.995      0.794
        16_dried_fruit        114        229      0.991      0.996      0.995      0.937
        17_dried_fruit        152        289      0.999          1      0.995      0.921
        18_dried_fruit        138        267      0.993      0.994      0.995       0.92
        19_dried_fruit        124        237      0.999      0.996      0.995      0.905
        20_dried_fruit         81        173      0.988       0.99      0.995      0.916
        21_dried_fruit        126        243      0.997          1      0.995      0.938
         22_dried_food        125        249      0.997      0.996      0.995      0.903
         23_dried_food        119        185          1      0.989      0.995      0.955
         24_dried_food        123        234      0.993      0.996      0.995      0.922
         25_dried_food         96        161      0.972          1      0.995       0.95
         26_dried_food        129        206      0.995          1      0.995      0.943
         27_dried_food        164        335      0.985          1      0.994      0.847
         28_dried_food        104        203      0.995          1      0.995      0.867
         29_dried_food         96        167      0.993          1      0.995      0.925
         30_dried_food        102        207      0.997          1      0.995      0.915
      31_instant_drink         82        163      0.992          1      0.995      0.894
      32_instant_drink        120        204          1      0.998      0.995      0.921
      33_instant_drink        100        204      0.997          1      0.995      0.886
      34_instant_drink        111        224      0.994          1      0.995      0.894
      35_instant_drink        143        291          1      0.982      0.995      0.874
      36_instant_drink        109        213      0.998          1      0.995      0.886
      37_instant_drink        104        197      0.977      0.995      0.995       0.94
      38_instant_drink         77        128      0.979      0.992      0.984      0.908
      39_instant_drink         99        192      0.993          1      0.995      0.883
      40_instant_drink        126        233      0.996      0.991      0.995      0.894
      41_instant_drink         87        143      0.993      0.994      0.995      0.904
    42_instant_noodles         93        196      0.993          1      0.995      0.899
    43_instant_noodles        119        227      0.988      0.987      0.995       0.88
    44_instant_noodles        136        266      0.974      0.974      0.993      0.912
    45_instant_noodles        122        233      0.998          1      0.995      0.876
    46_instant_noodles        130        239      0.996      0.998      0.995      0.878
    47_instant_noodles        115        230      0.996          1      0.995      0.899

ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123,
       124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185,
       186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x7b6c468a4920>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1, ...,           1,           1,           0],
       [          1,           1,           1, ...,           1,           1,           0],
       [          1,           1,           1, ...,           1,           1,           0],
       ...,
       [          1,           1,           1, ...,     0.60889,     0.60889,           0],
       [          1,           1,           1, ...,     0.55866,     0.55866,           0],
       [          1,           1,           1, ...,     0.13302,    0.066512,           0]]), 'Recall', 'Precision'], [array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,

In [ ]:
!pip install ultralytics --quiet
from ultralytics import YOLO

# Load a pretrained model
model = YOLO('yolov10s.pt') # 'n' for nano (fastest) or 's' for small

# Train
model.train(
    data='/kaggle/working/data.yaml',
    epochs=5,
    imgsz=640,
    batch=32,
    device=0 # Uses GPU
)

In [ ]:
import json
import pandas as pd

# Replace with your specific file path
file_path = '/kaggle/input/vista26/instances_val.json'

with open(file_path, 'r') as f:
    data = json.load(f)
print(data.keys())

In [16]:
import json
import pandas as pd

# Replace with your specific file path
file_path = '/kaggle/input/vista26/instances_val.json'

with open(file_path, 'r') as f:
    data = json.load(f)
print(data.keys())
val_images=data["images"]
#test_annotations = data["annotations"]
df_val_image=pd.DataFrame(val_images)
df_val_image.rename(columns = {'id':'image_id'}, inplace = True)
print(df_val_image.head(15))

dict_keys(['images'])
                     file_name  width  height  image_id   level
0   20180830-09-14-22-1444.jpg   1810    1810      2370    easy
1    20180913-10-42-28-385.jpg   1832    1832     28943    hard
2    20180912-13-17-58-200.jpg   1780    1780     27850    hard
3    20180917-10-14-10-872.jpg   1830    1830     29692    hard
4   20180829-13-33-55-1724.jpg   1852    1852      4012    easy
5   20180903-14-41-24-2632.jpg   1815    1815       513    easy
6   20181017-13-55-08-2143.jpg   1834    1834     13089  medium
7   20180829-15-04-31-1788.jpg   1838    1838      7587    easy
8    20180827-16-50-58-800.jpg   1822    1822      9431    easy
9   20181022-11-06-30-3023.jpg   1842    1842     11708  medium
10  20180830-16-52-01-2272.jpg   1836    1836      2498    easy
11  20180831-16-09-33-2455.jpg   1792    1792      8993    easy
12  20180919-09-12-30-1082.jpg   1838    1838     26637    hard
13  20180920-14-39-37-1228.jpg   1825    1825     26664    hard
14  20181017-16-57-19-2807.jpg   1814    1814     12430  medium

In [17]:
import yaml

agnostic_config = {
    'path': '/',          # Base path
    'train': '/kaggle/working/dataset/train_images.txt',            # Train images (relative to path)
    'val': '/kaggle/working/dataset/val_images.txt',
    'names': {
        0: 'item'  # Only one class now
    }
}

with open('/kaggle/working/data.yaml', 'w') as f:
    yaml.dump(agnostic_config, f, default_flow_style=False)

print("Agnostic data.yaml created.")

Agnostic data.yaml created.

In [18]:
import os

label_dir = '/kaggle/working/dataset/train/labels'

for label_file in os.listdir(label_dir):
    path = os.path.join(label_dir, label_file)
    with open(path, 'r') as f:
        lines = f.readlines()
    
    new_lines = []
    for line in lines:
        parts = line.split()
        parts[0] = '0'  # Change any class ID to 0
        new_lines.append(" ".join(parts))
        
    with open(path, 'w') as f:
        f.write("\n".join(new_lines))

In [ ]:
from ultralytics import YOLO

# Load the base YOLO26 model
model = YOLO('yolo26s.pt') 

# Fine-tune for Agnostic Detection
model.train(
    data='/kaggle/working/data.yaml',
    epochs=20,          # 25-50 is usually enough for agnostic specialization
    imgsz=640,         # High res for tiny product labels
    batch=-1,           # Auto-batch (finds the max your GPU can handle)
    augment=True,       # Crucial: enables mosaic and scale augmentations
    box=7.5,            # Increase box loss gain to prioritize coordinate precision
    cls=0.5,            # Lower class loss (since there's only 1 class)
    overlap_mask=True   # Helps the model distinguish between overlapping boxes
)

Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26s.pt to 'yolo26s.pt': 100% ━━━━━━━━━━━━ 19.5MB 209.0MB/s 0.1s
Ultralytics 8.4.9 🚀 Python-3.12.12 torch-2.8.0+cu126 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=True, auto_augment=randaugment, batch=-1, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/working/data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=20, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo26s.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=train2, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/runs/detect/train2, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  3                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  4                  -1  1    103360  ultralytics.nn.modules.block.C3k2            [128, 256, 1, False, 0.25]
  5                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  6                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5, 3, True]
 10                  -1  1    990976  ultralytics.nn.modules.block.C2PSA           [512, 512, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    477184  ultralytics.nn.modules.block.C3k2            [768, 256, 1, True]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    136192  ultralytics.nn.modules.block.C3k2            [512, 128, 1, True]
 17                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 20                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1843712  ultralytics.nn.modules.block.C3k2            [768, 512, 1, True, 0.5, True]
 23        [16, 19, 22]  1    932638  ultralytics.nn.modules.head.Detect           [1, 1, True, [128, 256, 512]]
YOLO26s summary: 260 layers, 9,948,638 parameters, 9,948,638 gradients, 22.5 GFLOPs

Transferred 696/708 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 2.5±3.3 ms, read: 499.9±171.8 MB/s, size: 280.9 KB)
train: Scanning /kaggle/working/dataset/train/labels... 14400 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 14400/14400 827.9it/s 17.4s<0.0s
train: New cache created: /kaggle/working/dataset/train/labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
AutoBatch: Computing optimal batch size for imgsz=640 at 60.0% CUDA memory utilization.
AutoBatch: CUDA:0 (Tesla T4) 14.56G total, 0.78G reserved, 0.33G allocated, 13.45G free
      Params      GFLOPs  GPU_mem (GB)  forward (ms) backward (ms)                   input                  output
     9948638        22.5         1.028         44.45           nan        (1, 3, 640, 640)                    list
     9948638          45         2.101         47.59           nan        (2, 3, 640, 640)                    list
     9948638       89.99         3.538         40.37           nan        (4, 3, 640, 640)                    list
     9948638         180         6.480         71.65           nan        (8, 3, 640, 640)                    list
     9948638         360        12.096         135.7           nan       (16, 3, 640, 640)                    list
AutoBatch: Using batch-size 10 for CUDA:0 8.92G/14.56G (61%) ✅
train: Fast image access ✅ (ping: 1.3±2.9 ms, read: 163.3±104.3 MB/s, size: 225.2 KB)
train: Scanning /kaggle/working/dataset/train/labels.cache... 14400 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 14400/14400 4.6Git/s 0.0s
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 8.5±4.2 ms, read: 77.6±47.6 MB/s, size: 270.5 KB)
val: Scanning /kaggle/working/dataset/train/labels... 3600 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 3600/3600 590.4it/s 6.1s0.0s
val: New cache created: /kaggle/working/dataset/train/labels.cache
Plotting labels to /kaggle/working/runs/detect/train2/labels.jpg...
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 114 weight(decay=0.0), 126 weight(decay=0.00046875), 126 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to /kaggle/working/runs/detect/train2
Starting training for 20 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/20      3.17G     0.8004     0.5984   0.006633        151        640: 100% ━━━━━━━━━━━━ 1440/1440 3.9it/s 6:13<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 180/180 4.3it/s 41.7s0.2ss
                   all       3600      43787      0.974      0.968      0.992      0.863

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/20      3.64G     0.7944     0.4085    0.00661        221        640: 100% ━━━━━━━━━━━━ 1440/1440 4.1it/s 5:50<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 180/180 4.7it/s 38.4s0.2ss
                   all       3600      43787      0.975      0.973      0.993      0.865

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/20      3.65G     0.7939     0.3872   0.006565        219        640: 100% ━━━━━━━━━━━━ 1440/1440 4.2it/s 5:47<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 180/180 4.7it/s 38.5s0.2ss
                   all       3600      43787      0.976      0.975      0.993      0.865

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/20      3.65G     0.7873     0.3809   0.006526        176        640: 100% ━━━━━━━━━━━━ 1440/1440 4.2it/s 5:45<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 180/180 4.7it/s 38.2s0.2ss
                   all       3600      43787      0.979      0.978      0.994      0.871

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/20      3.65G     0.7636     0.3566   0.006307        211        640: 100% ━━━━━━━━━━━━ 1440/1440 4.2it/s 5:45<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 180/180 4.7it/s 38.3s0.2ss
                   all       3600      43787      0.985      0.981      0.994      0.879

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/20      3.65G     0.7498     0.3424   0.006165        188        640: 100% ━━━━━━━━━━━━ 1440/1440 4.2it/s 5:45<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 180/180 4.4it/s 40.8s0.2ss
                   all       3600      43787      0.982      0.982      0.994      0.878

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/20      3.65G     0.7379     0.3318   0.006035        149        640: 100% ━━━━━━━━━━━━ 1440/1440 4.1it/s 5:50<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 180/180 4.7it/s 38.2s0.2ss
                   all       3600      43787      0.983      0.985      0.994      0.888

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/20      3.65G     0.7209     0.3183   0.005886        157        640: 100% ━━━━━━━━━━━━ 1440/1440 4.2it/s 5:44<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 180/180 4.7it/s 38.3s0.2ss
                   all       3600      43787      0.984      0.986      0.994      0.892

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/20      3.65G     0.7151     0.3132   0.005806        194        640: 96% ━━━━━━━━━━━╸ 1387/1440 4.2it/s 5:32<12.8s

In [19]:
!pip install ultralytics --quiet
from ultralytics import YOLO

# Load a pretrained model
model = YOLO('/kaggle/input/yolo-finetuned/pytorch/default/5/best_11s_agnostic_extra2.pt') # 'n' for nano (fastest) or 's' for small

# Train
model.train(
    data='/kaggle/working/data.yaml',
    epochs=30,
    imgsz=640,
    batch=32,
    device=0 # Uses GPU
)

Ultralytics 8.4.9 🚀 Python-3.12.12 torch-2.8.0+cu126 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/working/data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=30, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=/kaggle/input/yolo-finetuned/pytorch/default/5/best_11s_agnostic_extra2.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=train2, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/runs/detect/train2, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  3                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  4                  -1  1    103360  ultralytics.nn.modules.block.C3k2            [128, 256, 1, False, 0.25]
  5                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  6                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1    990976  ultralytics.nn.modules.block.C2PSA           [512, 512, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    443776  ultralytics.nn.modules.block.C3k2            [768, 256, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    127680  ultralytics.nn.modules.block.C3k2            [512, 128, 1, False]
 17                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1    345472  ultralytics.nn.modules.block.C3k2            [384, 256, 1, False]
 20                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1511424  ultralytics.nn.modules.block.C3k2            [768, 512, 1, True]
 23        [16, 19, 22]  1    819795  ultralytics.nn.modules.head.Detect           [1, 16, None, [128, 256, 512]]
YOLO11s summary: 182 layers, 9,428,179 parameters, 9,428,163 gradients, 21.5 GFLOPs

Transferred 499/499 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.7±0.4 ms, read: 493.5±126.8 MB/s, size: 248.1 KB)
train: Scanning /kaggle/working/dataset/train/labels... 14400 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 14400/14400 1.3Kit/s 11.4s0.1s
train: New cache created: /kaggle/working/dataset/train/labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.5±0.1 ms, read: 252.2±54.4 MB/s, size: 229.5 KB)
val: Scanning /kaggle/working/dataset/train/labels... 3600 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 3600/3600 743.1it/s 4.8s.0ss
val: New cache created: /kaggle/working/dataset/train/labels.cache
Plotting labels to /kaggle/working/runs/detect/train2/labels.jpg...
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.0005), 87 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to /kaggle/working/runs/detect/train2
Starting training for 30 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/30      8.26G      0.618     0.3068     0.9707        551        640: 100% ━━━━━━━━━━━━ 450/450 1.8it/s 4:15<0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.7it/s 33.6s0.6ss
                   all       3600      44057      0.995      0.994      0.995      0.895

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/30      8.15G     0.6462     0.3357     0.9855        637        640: 100% ━━━━━━━━━━━━ 450/450 1.8it/s 4:16<0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.7it/s 33.2s0.6ss
                   all       3600      44057      0.995      0.993      0.995      0.887

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/30      8.15G     0.6559     0.3449     0.9898        592        640: 100% ━━━━━━━━━━━━ 450/450 1.8it/s 4:13<0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.7it/s 33.7s0.6ss
                   all       3600      44057      0.989      0.987      0.995      0.879

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/30      8.21G     0.6654     0.3516      0.993        543        640: 100% ━━━━━━━━━━━━ 450/450 1.8it/s 4:13<0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.7it/s 33.4s0.6ss
                   all       3600      44057      0.993      0.994      0.995      0.883

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/30      8.07G     0.6572     0.3444     0.9911        648        640: 100% ━━━━━━━━━━━━ 450/450 1.8it/s 4:13<0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.7it/s 33.7s0.6ss
                   all       3600      44057      0.995      0.993      0.995      0.888

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/30      8.14G     0.6494     0.3367     0.9851        655        640: 100% ━━━━━━━━━━━━ 450/450 1.8it/s 4:13<0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.7it/s 33.7s0.6ss
                   all       3600      44057      0.994      0.993      0.995      0.891

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/30      8.13G     0.6431     0.3308     0.9823        652        640: 100% ━━━━━━━━━━━━ 450/450 1.8it/s 4:13<0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.7it/s 33.6s0.6ss
                   all       3600      44057      0.996      0.995      0.995      0.895

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/30      8.11G     0.6372      0.326     0.9782        529        640: 100% ━━━━━━━━━━━━ 450/450 1.8it/s 4:13<0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.7it/s 33.4s0.6ss
                   all       3600      44057      0.995      0.994      0.995      0.896

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/30      8.14G     0.6365     0.3222     0.9773        581        640: 100% ━━━━━━━━━━━━ 450/450 1.8it/s 4:13<0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.7it/s 33.7s0.6ss
                   all       3600      44057      0.997      0.995      0.995      0.895

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/30      8.21G     0.6276     0.3167     0.9732        566        640: 100% ━━━━━━━━━━━━ 450/450 1.8it/s 4:13<0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.7it/s 33.5s0.6ss
                   all       3600      44057      0.995      0.994      0.995      0.885

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/30      8.19G     0.6232      0.312      0.972        732        640: 100% ━━━━━━━━━━━━ 450/450 1.8it/s 4:13<0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.7it/s 33.7s0.6ss
                   all       3600      44057      0.997      0.995      0.995      0.889

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/30      8.21G     0.6207     0.3091     0.9708        592        640: 100% ━━━━━━━━━━━━ 450/450 1.8it/s 4:13<0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.7it/s 33.6s0.6ss
                   all       3600      44057      0.997      0.996      0.995      0.901

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/30      8.13G      0.615     0.3045     0.9674        658        640: 100% ━━━━━━━━━━━━ 450/450 1.8it/s 4:13<0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.7it/s 33.5s0.6ss
                   all       3600      44057      0.997      0.996      0.995      0.902

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/30      8.09G     0.6135     0.3013     0.9664        635        640: 100% ━━━━━━━━━━━━ 450/450 1.8it/s 4:13<0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.7it/s 33.4s0.6ss
                   all       3600      44057      0.997      0.997      0.995      0.903

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/30      7.84G     0.6084     0.2976     0.9611        524        640: 100% ━━━━━━━━━━━━ 450/450 1.8it/s 4:13<0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.7it/s 33.4s0.6ss
                   all       3600      44057      0.998      0.997      0.995      0.907

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/30      8.19G     0.6047     0.2944     0.9622        570        640: 100% ━━━━━━━━━━━━ 450/450 1.8it/s 4:13<0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.7it/s 33.5s0.6ss
                   all       3600      44057      0.997      0.997      0.995      0.907

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/30      8.05G     0.6022     0.2916      0.962        569        640: 100% ━━━━━━━━━━━━ 450/450 1.8it/s 4:13<0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.7it/s 33.5s0.6ss
                   all       3600      44057      0.998      0.997      0.995      0.907

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/30      8.16G      0.598     0.2892     0.9578        707        640: 100% ━━━━━━━━━━━━ 450/450 1.8it/s 4:13<0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.6it/s 34.9s0.6ss
                   all       3600      44057      0.998      0.997      0.995      0.909

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/30       8.1G     0.5925     0.2849     0.9556        679        640: 100% ━━━━━━━━━━━━ 450/450 1.8it/s 4:13<0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.7it/s 33.6s0.6ss
                   all       3600      44057      0.998      0.997      0.995       0.91

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/30      8.18G     0.5924     0.2824      0.956        609        640: 100% ━━━━━━━━━━━━ 450/450 1.8it/s 4:13<0.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.7it/s 33.6s0.6ss
                   all       3600      44057      0.998      0.998      0.995      0.911
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/30      8.13G     0.5125     0.2238     0.8962        413        640: 100% ━━━━━━━━━━━━ 450/450 1.8it/s 4:08<0.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.7it/s 33.2s0.6ss
                   all       3600      44057      0.998      0.997      0.995      0.911

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/30      8.14G     0.5085     0.2212     0.8921        387        640: 100% ━━━━━━━━━━━━ 450/450 1.8it/s 4:05<0.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.7it/s 33.5s0.6ss
                   all       3600      44057      0.998      0.997      0.995      0.912

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/30      8.14G     0.5038     0.2175     0.8935        373        640: 100% ━━━━━━━━━━━━ 450/450 1.8it/s 4:06<0.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.7it/s 33.3s0.6ss
                   all       3600      44057      0.998      0.997      0.995      0.912

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/30      8.13G     0.5019     0.2145     0.8918        393        640: 100% ━━━━━━━━━━━━ 450/450 1.8it/s 4:05<0.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.7it/s 33.5s0.6ss
                   all       3600      44057      0.998      0.998      0.995      0.912

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/30      8.14G     0.4982     0.2105     0.8914        387        640: 100% ━━━━━━━━━━━━ 450/450 1.8it/s 4:06<0.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.7it/s 33.9s0.6ss
                   all       3600      44057      0.999      0.998      0.995      0.914

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/30      8.13G     0.4952     0.2074     0.8901        384        640: 100% ━━━━━━━━━━━━ 450/450 1.8it/s 4:06<0.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.7it/s 33.6s0.6ss
                   all       3600      44057      0.999      0.997      0.995      0.914

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/30      8.15G      0.492     0.2043     0.8866        375        640: 100% ━━━━━━━━━━━━ 450/450 1.8it/s 4:06<0.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.7it/s 33.8s0.6ss
                   all       3600      44057      0.999      0.998      0.995      0.914

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/30      8.15G     0.4889     0.2013     0.8869        349        640: 100% ━━━━━━━━━━━━ 450/450 1.8it/s 4:06<0.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.7it/s 34.0s0.6ss
                   all       3600      44057      0.998      0.998      0.995      0.914

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/30      8.14G     0.4872     0.1987     0.8852        361        640: 100% ━━━━━━━━━━━━ 450/450 1.8it/s 4:05<0.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.7it/s 33.6s0.6ss
                   all       3600      44057      0.999      0.998      0.995      0.915

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/30      8.15G     0.4839     0.1965     0.8844        400        640: 100% ━━━━━━━━━━━━ 450/450 1.8it/s 4:05<0.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.7it/s 33.6s0.6ss
                   all       3600      44057      0.998      0.998      0.995      0.915

30 epochs completed in 2.382 hours.
Optimizer stripped from /kaggle/working/runs/detect/train2/weights/last.pt, 19.2MB
Optimizer stripped from /kaggle/working/runs/detect/train2/weights/best.pt, 19.2MB

Validating /kaggle/working/runs/detect/train2/weights/best.pt...
Ultralytics 8.4.9 🚀 Python-3.12.12 torch-2.8.0+cu126 CUDA:0 (Tesla T4, 14913MiB)
YOLO11s summary (fused): 101 layers, 9,413,187 parameters, 0 gradients, 21.3 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.5it/s 37.0s0.6ss
                   all       3600      44057      0.998      0.998      0.995      0.915
Speed: 0.2ms preprocess, 5.2ms inference, 0.0ms loss, 1.2ms postprocess per image
Results saved to /kaggle/working/runs/detect/train2

ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x793f8c9ac830>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,

In [17]:
!pip install ultralytics --quiet
from ultralytics import YOLO

# Load a pretrained model
model = YOLO('/kaggle/input/yolo-finetuned/pytorch/default/5/best_10s_agnostic.pt') # 'n' for nano (fastest) or 's' for small

# Train
model.train(
    data='/kaggle/working/data.yaml',
    epochs=10,
    imgsz=640,
    batch=32,
    amp=True,
    device=0,
    mosaic=1.0,
    mixup=0.1
)

Creating new Ultralytics Settings v0.0.6 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
Ultralytics 8.4.9 🚀 Python-3.12.12 torch-2.8.0+cu126 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/working/data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=10, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.1, mode=train, model=/kaggle/input/yolo-finetuned/pytorch/default/5/best_10s_agnostic.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=train, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/runs/detect/train, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 14.5MB/s 0.1s

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1     36096  ultralytics.nn.modules.block.SCDown          [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1    137728  ultralytics.nn.modules.block.SCDown          [256, 512, 3, 2]
  8                  -1  1    958464  ultralytics.nn.modules.block.C2fCIB          [512, 512, 1, True, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1    990976  ultralytics.nn.modules.block.PSA             [512, 512]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 17                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 20                  -1  1     68864  ultralytics.nn.modules.block.SCDown          [256, 256, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1089536  ultralytics.nn.modules.block.C2fCIB          [768, 512, 1, True, True]
 23        [16, 19, 22]  1   1639574  ultralytics.nn.modules.head.v10Detect        [1, [128, 256, 512]]
YOLOv10s summary: 235 layers, 8,067,126 parameters, 8,067,110 gradients, 24.8 GFLOPs

Transferred 619/619 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n.pt to 'yolo26n.pt': 100% ━━━━━━━━━━━━ 5.3MB 65.6MB/s 0.1s
AMP: checks passed ✅
train: Fast image access ✅ (ping: 1.0±1.1 ms, read: 381.2±84.5 MB/s, size: 190.4 KB)
train: Scanning /kaggle/working/dataset/train/labels... 14400 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 14400/14400 1.5Kit/s 9.8s<0.0s
train: New cache created: /kaggle/working/dataset/train/labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.4±0.0 ms, read: 516.7±80.3 MB/s, size: 257.4 KB)
val: Scanning /kaggle/working/dataset/train/labels... 3600 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 3600/3600 612.7it/s 5.9s.0ss
val: New cache created: /kaggle/working/dataset/train/labels.cache
Plotting labels to /kaggle/working/runs/detect/train/labels.jpg...
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 99 weight(decay=0.0), 112 weight(decay=0.0005), 111 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to /kaggle/working/runs/detect/train
Starting training for 10 epochs...
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/10      9.25G     0.5475     0.1926     0.9135        413        640: 100% ━━━━━━━━━━━━ 450/450 1.4it/s 5:15<0.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.2it/s 46.2s0.7ss
                   all       3600      44057      0.985       0.98      0.994      0.884

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/10      9.06G     0.5873      0.223      0.936        433        640: 100% ━━━━━━━━━━━━ 450/450 1.5it/s 5:06<0.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.5it/s 38.7s0.7ss
                   all       3600      44057      0.983      0.978      0.994      0.879

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/10      9.06G     0.5938     0.2299     0.9389        370        640: 100% ━━━━━━━━━━━━ 450/450 1.5it/s 5:03<0.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.5it/s 39.1s0.7ss
                   all       3600      44057      0.979      0.975      0.993      0.874

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/10      9.07G     0.5924       0.23     0.9357        397        640: 100% ━━━━━━━━━━━━ 450/450 1.5it/s 5:03<0.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.5it/s 39.1s0.7ss
                   all       3600      44057       0.98      0.973      0.993      0.873

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/10      9.07G     0.5771     0.2167     0.9317        369        640: 100% ━━━━━━━━━━━━ 450/450 1.5it/s 5:02<0.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.5it/s 39.1s0.7ss
                   all       3600      44057      0.982      0.982      0.994      0.885

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/10      9.07G     0.5603     0.1995     0.9233        425        640: 100% ━━━━━━━━━━━━ 450/450 1.5it/s 5:02<0.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.5it/s 39.1s0.7ss
                   all       3600      44057      0.989      0.985      0.995      0.896

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/10      9.06G     0.5471     0.1898     0.9159        406        640: 100% ━━━━━━━━━━━━ 450/450 1.5it/s 5:02<0.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.5it/s 39.3s0.7ss
                   all       3600      44057      0.992      0.991      0.995        0.9

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/10      9.07G     0.5338     0.1793     0.9075        369        640: 100% ━━━━━━━━━━━━ 450/450 1.5it/s 5:02<0.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.5it/s 38.9s0.7ss
                   all       3600      44057      0.992      0.991      0.995      0.904

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/10      9.07G     0.5251      0.173     0.9057        384        640: 100% ━━━━━━━━━━━━ 450/450 1.5it/s 5:01<0.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.5it/s 39.0s0.7ss
                   all       3600      44057      0.994      0.992      0.995      0.907

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/10      9.07G     0.5158     0.1667     0.9017        361        640: 100% ━━━━━━━━━━━━ 450/450 1.5it/s 5:01<0.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.5it/s 39.0s0.7ss
                   all       3600      44057      0.994      0.993      0.995      0.908

10 epochs completed in 0.958 hours.
Optimizer stripped from /kaggle/working/runs/detect/train/weights/last.pt, 16.5MB
Optimizer stripped from /kaggle/working/runs/detect/train/weights/best.pt, 16.5MB

Validating /kaggle/working/runs/detect/train/weights/best.pt...
Ultralytics 8.4.9 🚀 Python-3.12.12 torch-2.8.0+cu126 CUDA:0 (Tesla T4, 14913MiB)
YOLOv10s summary (fused): 106 layers, 7,218,387 parameters, 0 gradients, 21.4 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 57/57 1.5it/s 37.1s0.6ss
                   all       3600      44057      0.994      0.993      0.995      0.908
Speed: 0.2ms preprocess, 6.3ms inference, 0.0ms loss, 0.2ms postprocess per image
Results saved to /kaggle/working/runs/detect/train

ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x793f29a2d700>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,     0.99993,     0.99992,     0.99992,
            0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,
            0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,
            0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,
            0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,
            0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,
            0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,     0.99992,

In [22]:
import os
import yaml
import cv2
import pandas as pd
import torch
from ultralytics import YOLO
from tqdm import tqdm
from torchvision.ops import box_iou, nms
# 1. Load data.yaml for validation paths
yaml_path = '/kaggle/working/data.yaml'
with open(yaml_path, 'r') as f:
    data_config = yaml.safe_load(f)

val_source = data_config.get('val')
if val_source.endswith('.txt'):
    with open(val_source, 'r') as f:
        image_paths = [line.strip() for line in f.readlines()]
else:
    image_paths = [os.path.join(val_source, f) for f in os.listdir(val_source) 
                   if f.endswith(('.jpg', '.png', '.jpeg'))]

# 1. Setup Models
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ENSEMBLE: Two Agnostic Detectors (The "Counters")
detector1 = YOLO('/kaggle/working/runs/detect/train2/weights/best.pt') 
detector2 = YOLO('/kaggle/input/yolo-finetuned/pytorch/default/6/best_11s_agnostic3.pt') 
detector3 = YOLO('/kaggle/input/yolo-finetuned/pytorch/default/6/best_10s_agnostic2.pt')
# Classifier (The "Labeler")
classifier = YOLO('/kaggle/working/runs/detect/train/weights/best.pt')

# ... (image_paths and val_labels_path setup remains the same) ...
val_labels_path = '/kaggle/working/dataset/train/labels'

results_comparison = []

# 3. Ensemble Evaluation Loop
for img_path in tqdm(image_paths[:3600], desc="Validating Dual-Detector Ensemble"):
    img_name = os.path.basename(img_path)
    
    # --- A. Get Ground Truth ---
    label_file = os.path.splitext(img_name)[0] + '.txt'
    label_path = os.path.join(val_labels_path, label_file)
    gt_categories = []
    if os.path.exists(label_path):
        with open(label_path, 'r') as f:
            for line in f:
                gt_categories.append(int(line.split()[0]) + 1)
    
    # --- B. Ensemble Prediction ---
    
    # 1. Get Detections from both detectors
    res1 = detector1(img_path, conf=0.45, iou=0.45, verbose=False)[0]
    res2 = detector2(img_path, conf=0.45, iou=0.45, verbose=False)[0]
    res3 = detector3(img_path, conf=0.45, iou=0.45, verbose=False)[0]
    # Combine boxes and scores for NMS
    all_det_boxes = torch.cat([res1.boxes.xyxy, res2.boxes.xyxy, res3.boxes.xyxy])
    all_det_scores = torch.cat([res1.boxes.conf, res2.boxes.conf, res3.boxes.conf])
    
    # 2. Merge overlapping boxes from the two detectors
    # iou_threshold=0.5 means if boxes overlap by 50%, keep only the higher confidence one
    keep_indices = nms(all_det_boxes, all_det_scores, iou_threshold=0.5)
    det_boxes = all_det_boxes[keep_indices]
    
    # 3. Run Labeling Model
    cls_results = classifier(img_path, conf=0.45, iou=0.45, verbose=False)
    cls_boxes = cls_results[0].boxes.xyxy
    cls_labels = cls_results[0].boxes.cls
    
    pred_categories = []

    # 4. Logic: Match Merged Agnostic boxes to Classifier labels
    if len(det_boxes) > 0:
        if len(cls_boxes) > 0:
            ious = box_iou(det_boxes, cls_boxes)
            for i in range(len(det_boxes)):
                max_iou, max_idx = torch.max(ious[i], dim=0)
                if max_iou > 0.15:
                    pred_categories.append(int(cls_labels[max_idx]) + 1)
                else:
                    pred_categories.append(1) 
        else:
            pred_categories = [1] * len(det_boxes)

    # --- C. Compare Results ---
    results_comparison.append({
        'image': img_name,
        'gt_count': len(gt_categories),
        'pred_count': len(pred_categories),
        'is_perfect_count': len(gt_categories) == len(pred_categories),
        'is_perfect_labels': sorted(gt_categories) == sorted(pred_categories)
    })

# 4. Analysis
df_perf = pd.DataFrame(results_comparison)
print(f"\n--- Dual-Detector Spatial Ensemble Results ---")
print(f"Perfect Count Accuracy: {df_perf['is_perfect_count'].mean() * 100:.2f}%")
print(f"Perfect Label Accuracy: {df_perf['is_perfect_labels'].mean() * 100:.2f}%")

Validating Dual-Detector Ensemble: 100%|██████████| 3600/3600 [06:30<00:00,  9.22it/s]

--- Dual-Detector Spatial Ensemble Results ---
Perfect Count Accuracy: 97.67%
Perfect Label Accuracy: 0.00%

In [25]:
import os
import yaml
import cv2
import pandas as pd
import torch
from ultralytics import YOLO
from tqdm import tqdm
from torchvision.ops import box_iou, nms
# 1. Load data.yaml for validation paths
yaml_path = '/kaggle/working/data.yaml'
with open(yaml_path, 'r') as f:
    data_config = yaml.safe_load(f)

val_source = data_config.get('val')
if val_source.endswith('.txt'):
    with open(val_source, 'r') as f:
        image_paths = [line.strip() for line in f.readlines()]
else:
    image_paths = [os.path.join(val_source, f) for f in os.listdir(val_source) 
                   if f.endswith(('.jpg', '.png', '.jpeg'))]

# 1. Setup Models
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ENSEMBLE: Two Agnostic Detectors (The "Counters")
detector1 = YOLO('/kaggle/input/yolo-finetuned/pytorch/default/6/best_11s_agnostic3.pt') 
detector2 = YOLO('/kaggle/working/runs/detect/train2/weights/best.pt') 

# Classifier (The "Labeler")
classifier1 = YOLO('/kaggle/working/runs/detect/train/weights/best.pt')
classifier2 = YOLO('/kaggle/input/yolo-finetuned/pytorch/default/6/best.pt')
# ... (image_paths and val_labels_path setup remains the same) ...
val_labels_path = '/kaggle/working/dataset/train/labels'

results_comparison = []

# 3. Ensemble Evaluation Loop
for img_path in tqdm(image_paths[:3600], desc="Validating Dual-Detector Ensemble"):
    img_name = os.path.basename(img_path)
    
    # --- A. Get Ground Truth ---
    label_file = os.path.splitext(img_name)[0] + '.txt'
    label_path = os.path.join(val_labels_path, label_file)
    gt_categories = []
    if os.path.exists(label_path):
        with open(label_path, 'r') as f:
            for line in f:
                gt_categories.append(int(line.split()[0]) + 1)
    
    # --- B. Ensemble Prediction ---
    
    # 1. Get Detections from both detectors
    res1 = detector1(img_path, conf=0.45, iou=0.45, verbose=False)[0]
    res2 = detector2(img_path, conf=0.45, iou=0.45, verbose=False)[0]
    
    # Combine boxes and scores for NMS
    all_det_boxes = torch.cat([res1.boxes.xyxy, res2.boxes.xyxy])
    all_det_scores = torch.cat([res1.boxes.conf, res2.boxes.conf])
    
    # 2. Merge overlapping boxes from the two detectors
    # iou_threshold=0.5 means if boxes overlap by 50%, keep only the higher confidence one
    keep_indices = nms(all_det_boxes, all_det_scores, iou_threshold=0.5)
    det_boxes = all_det_boxes[keep_indices]
    
    # --- C. Classifier Ensemble (The "What") ---
    # Run both classifiers
    cls1_res = classifier1(img_path, conf=0.25, verbose=False)[0]
    cls2_res = classifier2(img_path, conf=0.25, verbose=False)[0]
    
    # Extract boxes, labels, AND confidence scores
    c1_boxes, c1_labels, c1_conf = cls1_res.boxes.xyxy, cls1_res.boxes.cls, cls1_res.boxes.conf
    c2_boxes, c2_labels, c2_conf = cls2_res.boxes.xyxy, cls2_res.boxes.cls, cls2_res.boxes.conf
    
    pred_categories = []

    # 4. Logic: Match Detector Boxes to the BEST Classifier Label
    if len(det_boxes) > 0:
        for i in range(len(det_boxes)):
            # Check overlap with Classifier 1
            iou1 = box_iou(det_boxes[i].unsqueeze(0), c1_boxes) if len(c1_boxes) > 0 else torch.tensor([])
            # Check overlap with Classifier 2
            iou2 = box_iou(det_boxes[i].unsqueeze(0), c2_boxes) if len(c2_boxes) > 0 else torch.tensor([])
            
            match1_idx = torch.argmax(iou1) if iou1.numel() > 0 else -1
            match2_idx = torch.argmax(iou2) if iou2.numel() > 0 else -1
            
            # --- The Voting Logic ---
            best_label = 0 # Default to Background (1-indexed becomes class 1)
            
            # Get predictions and confidences from matches
            label1 = int(c1_labels[match1_idx]) + 1 if (match1_idx != -1 and iou1[0, match1_idx] > 0.15) else None
            conf1 = float(c1_conf[match1_idx]) if label1 else 0
            
            label2 = int(c2_labels[match2_idx]) + 1 if (match2_idx != -1 and iou2[0, match2_idx] > 0.15) else None
            conf2 = float(c2_conf[match2_idx]) if label2 else 0

            if label1 and label2:
                if label1 == label2:
                    best_label = label1 # Both agree
                else:
                    # Disagreement: Pick the one with higher confidence
                    best_label = label1 if conf1 > conf2 else label2
            elif label1:
                best_label = label1
            elif label2:
                best_label = label2
            else:
                best_label = 1 # Fallback to class 1
                
            pred_categories.append(best_label)
            
    # --- C. Compare Results ---
    results_comparison.append({
        'image': img_name,
        'gt_count': len(gt_categories),
        'pred_count': len(pred_categories),
        'is_perfect_count': len(gt_categories) == len(pred_categories),
        'is_perfect_labels': sorted(gt_categories) == sorted(pred_categories)
    })

# 4. Analysis
df_perf = pd.DataFrame(results_comparison)
print(f"\n--- Dual-Detector Spatial Ensemble Results ---")
print(f"Perfect Count Accuracy: {df_perf['is_perfect_count'].mean() * 100:.2f}%")
print(f"Perfect Label Accuracy: {df_perf['is_perfect_labels'].mean() * 100:.2f}%")

Validating Dual-Detector Ensemble: 100%|██████████| 3600/3600 [07:06<00:00,  8.45it/s]

--- Dual-Detector Spatial Ensemble Results ---
Perfect Count Accuracy: 97.78%
Perfect Label Accuracy: 0.00%

In [ ]:
import pandas as pd
import json
import os
import torch
import numpy as np
from ultralytics import YOLO
from tqdm import tqdm
from torchvision.ops import box_iou, nms

# 1. Setup Models
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ENSEMBLE: Two Agnostic Detectors (The "Counters")
detector1 = YOLO('/kaggle/input/yolo-finetuned/pytorch/default/7/best_26s_agnostic.pt') 
detector2 = YOLO('/kaggle/input/yolo-finetuned/pytorch/default/6/best_11s_agnostic3.pt') 

# ENSEMBLE: Two Classifiers (The "Labelers")
classifier1 = YOLO('/kaggle/working/runs/detect/train/weights/best.pt')
classifier2 = YOLO('/kaggle/input/yolo-finetuned/pytorch/default/7/best_11s2.pt') # Replace with your 2nd classifier path

val_images_path = '/kaggle/input/vista26/Vistas Dataset Public/Vistas Dataset Public/validation'
# Assuming df_val_image is pre-loaded
id_map = dict(zip(df_val_image['file_name'], df_val_image['image_id']))

submission_data = []

# 3. Inference Loop
for file_name, image_id in tqdm(id_map.items(), desc="Spatial Ensemble"):
    img_path = os.path.join(val_images_path, file_name)
    
    if not os.path.exists(img_path):
        submission_data.append({'image_id': int(image_id), 'categories': "[]"})
        continue

    # --- Step 1: Agnostic Detection Ensemble ---
    res1 = detector1(img_path, conf=0.45, iou=0.45, verbose=False)[0]
    res2 = detector2(img_path, conf=0.45, iou=0.45, verbose=False)[0]
    
    all_det_boxes = torch.cat([res1.boxes.xyxy, res2.boxes.xyxy])
    all_det_scores = torch.cat([res1.boxes.conf, res2.boxes.conf])
    
    if len(all_det_boxes) == 0:
        submission_data.append({'image_id': int(image_id), 'categories': "[]"})
        continue

    # Merge agnostic boxes
    keep_indices = nms(all_det_boxes, all_det_scores, iou_threshold=0.5)
    det_boxes = all_det_boxes[keep_indices]

    # --- Step 2: Run Both Classifiers (Detectors used as labelers) ---
    cls1_res = classifier1(img_path, conf=0.25, iou=0.45, verbose=False)[0]
    cls2_res = classifier2(img_path, conf=0.25, iou=0.45, verbose=False)[0]

    c1_boxes, c1_labels, c1_conf = cls1_res.boxes.xyxy, cls1_res.boxes.cls, cls1_res.boxes.conf
    c2_boxes, c2_labels, c2_conf = cls2_res.boxes.xyxy, cls2_res.boxes.cls, cls2_res.boxes.conf

    predicted_cats = []

    # --- Step 3: Spatial Gating with Confidence Voting ---
    for i in range(len(det_boxes)):
        current_box = det_boxes[i].unsqueeze(0)
        
        # Find best match in Classifier 1
        iou1 = box_iou(current_box, c1_boxes) if len(c1_boxes) > 0 else torch.tensor([])
        match1_idx = torch.argmax(iou1) if iou1.numel() > 0 else -1
        
        # Find best match in Classifier 2
        iou2 = box_iou(current_box, c2_boxes) if len(c2_boxes) > 0 else torch.tensor([])
        match2_idx = torch.argmax(iou2) if iou2.numel() > 0 else -1
        
        # Get Candidate 1
        label1, conf1 = None, 0
        if match1_idx != -1 and iou1[0, match1_idx] > 0.15:
            label1 = int(c1_labels[match1_idx]) + 1
            conf1 = float(c1_conf[match1_idx])
            
        # Get Candidate 2
        label2, conf2 = None, 0
        if match2_idx != -1 and iou2[0, match2_idx] > 0.15:
            label2 = int(c2_labels[match2_idx]) + 1
            conf2 = float(c2_conf[match2_idx])

        # --- Max Confidence Voting ---
        if label1 and label2:
            # If they both see it, pick the one that is more confident
            predicted_cats.append(label1 if conf1 >= conf2 else label2)
        elif label1:
            predicted_cats.append(label1)
        elif label2:
            predicted_cats.append(label2)
        else:
            # Neither classifier matched this box well enough
            predicted_cats.append(1)

    # Final Submission Formatting
    submission_data.append({
        'image_id': int(image_id),
        'categories': json.dumps(sorted(predicted_cats), separators=(',', ':'))
    })

# 4. Save
submission_df = pd.DataFrame(submission_data).sort_values(by='image_id').reset_index(drop=True)
submission_df.to_csv('/kaggle/working/submission.csv', index=False)

Spatial Ensemble:  46%|████▋     | 2776/6000 [07:44<07:12,  7.45it/s]